### ISSUE TITLE
amissl does not link

### ISSUE THREAD

**Issue by githubaf** [bebbo/gcc#81]
Out of curiosity I tried to compile https://github.com/jens-maus/amissl with your gcc.

Compilation/linking works with gcc 2.95 from https://github.com/adtools/amigaos-cross-toolchain

With your gcc it failes after a while with

```
#Compiled with
PATH=~/opt/m68k-amigaos_26Feb19/bin:$PATH make OS=os3


m68k-amigaos-gcc -mcrt=clib2 -m68020-60 -W -Wall -Wno-unused -O0 -g -gstabs -D__NO_NET_API -DB_ENDIAN -DOPENSSL_SYS_AMIGA -DOPENSSL_NO_STDIO -D__C_MACROS__ -DBN_DEBUG -DCONF_DEBUG -DDEBUG -DNO_INLINE_VARARGS -D__amigaos3__ -I../../include -I../../include/netinclude   -Iinclude -I../../openssl/include  -c -o test/afalgtest.o ../../openssl/test/afalgtest.c
rm -f test/afalgtest
${LDCMD:-m68k-amigaos-gcc} -mcrt=clib2 -m68020-60 -W -Wall -Wno-unused -O0 -g -gstabs -L. -L.. -mcrt=clib2 -resident32  \
                -o test/afalgtest test/afalgtest.o \
                test/libtestutil.a -lamisslauto -lamisslstubs -lamissldebug -lm 
/home/developer/opt/m68k-amigaos_26Feb19/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /home/developer/opt/m68k-amigaos_26Feb19/m68k-amigaos/clib2/lib/libm020/libb32/libc.a(stdlib_main.o):(.text+0x9e): undefined reference to `main'

```

Are there additional options necessary with your compiler?

**Comment by bebbo** [comment]
it failes more early
```
m68k-amigaos-gcc: error: unrecognized command line option '-mrestore-a4'
```

**Comment by arczi84** [comment]
I've compiled AmiSSL with `gcc version 6.5.0b 191023121710 (GCC)` out of the box with make OS=os3.
When launching NetSurf I get: `Couldn't initialize amisslmaster.library!`
SnoopDOS says it's loaded.

**Comment by arczi84** [comment]
Amissl build fails here

> /d/amiga-gcc2/bin/m68k-amigaos-ld: ./build_os3/amisslmaster_libinit.o: in function `LibOpen':
> src/amisslmaster_libinit.c:864: undefined reference to `__restore_a4'
> /d/amiga-gcc2/bin/m68k-amigaos-ld: ./build_os3/amisslmaster_libinit.o: in function `LibInit':
> src/amisslmaster_libinit.c:616: undefined reference to `__restore_a4'
> /d/amiga-gcc2/bin/m68k-amigaos-ld: ./build_os3/amisslmaster_libinit.o: in function `LibExpunge':
> src/amisslmaster_libinit.c:798: undefined reference to `__restore_a4'
> /d/amiga-gcc2/bin/m68k-amigaos-ld: ./build_os3/amisslmaster_libinit.o: in function `LibClose':
> src/amisslmaster_libinit.c:1106: undefined reference to `__restore_a4'

**Comment by bebbo** [comment]
any updates here?

**Comment by arczi84** [comment]
Sorry bebbo, forgot about this thread.

I can't compile NetSurf with latest builds unfortunately but IIRC I could build AmiSSL.

**Comment by bebbo** [comment]
what's the problem with netsurf?

**Comment by arczi84** [comment]
Errors like these appeared:

`In file included from D:/amiga-gcc2/m68k-amigaos/clib2/include/stdlib.h:43:0,
                 from /e/opt/netsurf/share/include/libcss/types.h:18,
                 from /e/opt/netsurf/share/include/libcss/libcss.h:19,
                 from content/handlers/css/utils.h:22,
                 from desktop/treeview.c:42:
D:/amiga-gcc2/m68k-amigaos/sys-include/stdlib.h: In function 'reallocarray':
D:/amiga-gcc2/m68k-amigaos/sys-include/stdlib.h:146:54: error: unknown type name '__result_use_check'
 __stdargs void *reallocarray(void *, size_t, size_t) __result_use_check __alloc_size((2,3));
                                                      ^~~~~~~~~~~~~~~~~~`

**Comment by arczi84** [comment]
Compiles with original clib2 headers.

**Comment by bebbo** [comment]
closing - you better open tickets at amissl.
